glslangvalidator -V debug.vert -o debug.vert.spv
glslangvalidator -V debug.frag -o debug.frag.spv
glslangvalidator -V deferred.vert -o deferred.vert.spv
glslangvalidator -V deferred.frag -o deferred.frag.spv
glslangvalidator -V mrt.vert -o mrt.vert.spv
glslangvalidator -V mrt.frag -o mrt.frag.spv
glslangvalidator -V texture.frag -o texture.frag.spv
glslangvalidator -V texture.vert -o texture.vert.spv
glslangvalidator -V raytracing.comp -o raytracing.comp.spv
